"""acepta nulls

Revision ID: 2474113301e0
Revises: f15734961aa4
Create Date: 2026-05-20 21:45:44.556554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2474113301e0'
down_revision: Union[str, Sequence[str], None] = 'f15734961aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_drive_files', 'last_known_modified_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('google_drive_files', 'last_synced_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_drive_files', 'last_synced_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('google_drive_files', 'last_known_modified_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
