"""mapear claves foreaneas

Revision ID: 43529d377aa7
Revises: 8ac2e0eefa4e
Create Date: 2026-05-27 19:53:46.120166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43529d377aa7'
down_revision: Union[str, Sequence[str], None] = '8ac2e0eefa4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
