"""crear googledrivefiledocument

Revision ID: 8ac2e0eefa4e
Revises: 2474113301e0
Create Date: 2026-05-26 21:36:06.186721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ac2e0eefa4e'
down_revision: Union[str, Sequence[str], None] = '2474113301e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_drive_file_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drive_file_id', sa.String(length=255), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['drive_file_id'], ['google_drive_files.drive_file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_file_id')
    )
    op.create_index('idx_google_drive_file_documents_search_vector', 'google_drive_file_documents', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('google_drive_files', 'last_known_modified_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('google_drive_files', 'last_synced_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_drive_files', 'last_synced_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('google_drive_files', 'last_known_modified_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index('idx_google_drive_file_documents_search_vector', table_name='google_drive_file_documents', postgresql_using='gin')
    op.drop_table('google_drive_file_documents')
    # ### end Alembic commands ###
