"""crear google drive file

Revision ID: f15734961aa4
Revises: f2ede7770cc1
Create Date: 2026-05-20 15:27:13.857931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f15734961aa4'
down_revision: Union[str, Sequence[str], None] = 'f2ede7770cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_drive_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('drive_file_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('parent_drive_file_id', sa.String(length=255), nullable=True),
    sa.Column('drive_web_view_link', sa.String(length=500), nullable=True),
    sa.Column('last_known_modified_time', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_drive_file_id'], ['google_drive_files.drive_file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_file_id')
    )
    op.create_index('idx_google_drive_files_area_id', 'google_drive_files', ['area_id'], unique=False)
    op.create_index('idx_google_drive_files_drive_file_id', 'google_drive_files', ['drive_file_id'], unique=False)
    op.create_index('idx_google_drive_files_last_known_modified_time', 'google_drive_files', ['last_known_modified_time'], unique=False)
    op.create_index('idx_google_drive_files_parent_drive_file_id', 'google_drive_files', ['parent_drive_file_id'], unique=False)
    op.alter_column('google_drive_sync_states', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_drive_sync_states', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_google_drive_files_parent_drive_file_id', table_name='google_drive_files')
    op.drop_index('idx_google_drive_files_last_known_modified_time', table_name='google_drive_files')
    op.drop_index('idx_google_drive_files_drive_file_id', table_name='google_drive_files')
    op.drop_index('idx_google_drive_files_area_id', table_name='google_drive_files')
    op.drop_table('google_drive_files')
    # ### end Alembic commands ###
